events {}

http {
    resolver 127.0.0.11 valid=30s; refer to Docker’s internal DNS server

    upstream backend {
        server app_v1:5000 weight=9; 90% to stable
        server app_v2:5000 weight=1; 10% to canary
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}